sudo: required
services:
  - docker

before_install:
  - docker build -t emanewere/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true emanewere/react-test npm test

after_success:
  - docker build -t emanewere/multi-client-2 ./client
  - docker build -t emanewere/multi-nginx-2 ./nginx
  - docker build -t emanewere/multi-server-2 ./server
  - docker build -t emanewere/multi-worker-2 ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push emanewere/multi-client-2
  - docker push emanewere/multi-nginx-2
  - docker push emanewere/multi-server-2
  - docker push emanewere/multi-worker-2
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-824508926069'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
